baseURL: /
relativeURLs: true
languageCode: fr-FR
title: Les Rougon-Macquart
theme: "rougon"

enableRobotsTXT: true

outputs:
  home:
    - html
    - json

blackfriday:
  extensions: ["hardLineBreak"]
  hrefTargetBlank: true