baseURL: http://localhost:1313
relativeURLs: true
languageCode: fr-FR
title: Les Rougon-Macquart
theme:
  - hugoAPI
  - rougon


enableRobotsTXT: true

paginate: 5

outputs:
  home:
    - html
    - json
  page: 
    - html
    - json
  section:
    - html
    - json

blackfriday:
  extensions: ["hardLineBreak"]
  hrefTargetBlank: true

params:
  apiurl: false
  pagination: 5
  algolia:
    vars: ["title", "relpermalink", "novels", "human_title"]
    params: ["main_name", "secondary_name", "name_suffix", "novel"]


related:
  includeNewer: true # Hugo ignores newer posts by default, we want them.
  indices:
    - name: novel # The name of the indice, and the page's .Param to use here.
      weight: 1 # We don't really need this, but omitting it would disable the indice.

outputFormats:
  Algolia:
    baseName: algolia
    isPlainText: true
    mediaType: "application/json"
    notAlternative: true

