baseURL: /
relativeURLs: true
languageCode: fr-FR
title: Les Rougon-Macquart
theme: 
  - rougon
  - juliette-hugo-component
enableRobotsTXT: true

outputs:
  home:
    - html
    - json
    - Algolia
    - redirect_netlify
  section:
   - html
   - json
   - xml
  page:
   - html
   - json

blackfriday:
  extensions: ["hardLineBreak"]
  hrefTargetBlank: true

params:
  algolia:
    vars: ["title", "relpermalink"]
    params: ["main_name", "secondary_name", "name_suffix", "novel"]
  juliette:
    pagination: 10
    slug: api
    beautify: true

related:
  includeNewer: true # Hugo ignores newer posts by default, we want them.
  indices:
    - name: novel # The name of the indice, and the page's .Param to use here.
      weight: 1 # We don't really need this, but omitting it would disable the indice.

outputFormats:
  Algolia:
    baseName: algolia
    isPlainText: true
    mediaType: "application/json"
    notAlternative: true

