baseURL: /
relativeURLs: true
languageCode: fr-FR
title: Les Rougon-Macquart
theme: "rougon"

defaultContentLanguage: fr

languages:
  fr:
    weight: 10
    languageName: Français
    contentDir: "contentFr"
  en:
    weight: 10
    languageName: English
    contentDir: "contentEn"

enableRobotsTXT: true

outputs:
  home:
    - html
    - json

blackfriday:
  extensions: ["hardLineBreak"]
  hrefTargetBlank: true

related:
  includeNewer: true # Hugo ignores newer posts by default, we want them.
  indices:
    - name: novel # The name of the indice, and the page's .Param to use here.
      weight: 1 # We don't really need this, but omitting it would disable the indice.