baseURL: /
relativeURLs: true
languageCode: fr-FR
title: Les Rougon-Macquart
theme: "rougon"

enableRobotsTXT: true

outputs:
  home:
    - html
    - json
    - Algolia

blackfriday:
  extensions: ["hardLineBreak"]
  hrefTargetBlank: true

params:
  algolia:
    vars: ["title", "relpermalink", "novels", "human_title"]
    params: ["main_name", "secondary_name", "name_suffix", "novel"]

outputFormats:
  Algolia:
    baseName: algolia
    isPlainText: true
    mediaType: "application/json"
    notAlternative: true