[build]
    publish = "public"
    command = "npm run rougon"

[context.production.environment]
    HUGO_VERSION = "0.33"
    HUGO_ENV = "production"

[context.deploy-preview.environment]
	HUGO_VERSION = "0.33"

[context.branch-deploy.environment]
  	HUGO_VERSION = "0.33"

[context.stage.environment]
	HUGO_BASEURL = "https://stage.rougon-macquart.com/"
	HUGO_ENV = "stage"