[build]
    publish = "public"
    command = "npm run rougon"

[context.production.environment]
    HUGO_VERSION = "0.33"

[context.deploy-preview.environment]
	HUGO_VERSION = "0.33"

[context.stage.environment]
	HUGO_VERSION = "0.33"